[package]
name = "drep"
version = "0.0.1"
edition = "2024"
description = "A Rust documentation generator"
repository = "https://github.com/xandwr/rustdoc"
license = "MIT OR Apache-2.0"

[dependencies]
